kramdown:
  input: GFM
  toc_levels: 2..3

baseurl: "/aerys"
layouts_dir: ".shared/layout"

exclude: ["Gemfile", "Gemfile.lock", "README.md", "vendor"]
include: [".shared"]

repository: amphp/aerys
gems:
 - "jekyll-github-metadata"
 - "jekyll-relative-links"

defaults:
 - scope:
     path: ""
     type: "pages"
   values:
     layout: "docs"

asset_path: "/aerys/.shared/asset"

navigation:
 - http
 - websocket
 - host
 - io
 - helpers
 - logging
 - options
 - http-advanced
 - performance
 - middlewares
 - production
 - more
 - classes