kramdown:
  input: GFM
  toc_levels: 2..3

baseurl: "/aerys"
layouts_dir: ".shared/layout"
includes_dir: ".shared/includes"

exclude: ["Gemfile", "Gemfile.lock", "README.md", "vendor"]
safe: true

repository: amphp/aerys
gems:
 - "jekyll-github-metadata"
 - "jekyll-relative-links"

defaults:
 - scope:
     path: ""
     type: "pages"
   values:
     layout: "docs"
     description: "Aerys is a non-blocking HTTP/1.1 and HTTP/2 application, WebSocket and static file server written in PHP based on Amp."
     keywords: ["amphp", "amp", "aerys", "http server", "http", "server", "application server", "php"]

shared_asset_path: "/aerys/asset"

navigation:
 - http
 - websocket
 - host
 - io
 - helpers
 - logging
 - options
 - http-advanced
 - performance
 - filters
 - production
 - more
 - classes
