kramdown:
  input: GFM
  toc_levels: 2..3

baseurl: "/aerys"
data_dir: "_data"

exclude: ["Gemfile", "Gemfile.lock", "README.md", "vendor"]
include: [".shared"]

repository: amphp/aerys
gems:
 - "jekyll-github-metadata"
 - "jekyll-relative-links"

defaults:
 - scope:
     path: ""
     type: "pages"
   values:
     layout: "docs"

asset_path: "/aerys/.shared/asset"